# fly.toml app configuration file generated for enhs99-dev-site on 2023-10-14T19:45:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "enhs99-dev-site"
primary_region = "otp"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
